[package]
name = "miniprot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniprot-sys = { path = "./miniprot-sys" }
lazy_static = "1.4.0"